#COMPONENT_ADD_INCLUDEDIRS := . MQTTClient-C/ MQTTClient-C/mbedtls MQTTClient-C/Platform_ESP32 MQTTPacket/ 
COMPONENT_ADD_INCLUDEDIRS := . MQTTClient-C/ MQTTClient-C/Platform_ESP32 MQTTPacket/ 
COMPONENT_SRCDIRS := $(COMPONENT_ADD_INCLUDEDIRS)